name: Cythonize Python Script

on:
  push:
    branches:
      - README.md
  pull_request:
    branches:
      - README.md

jobs:
  build:
    runs-on: linux-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython setuptools

      - name: Cythonize and build
        run: |
          python setup.py build_ext --inplace

      - name: Move
        run: mkdir cpy && mv cl.cpython-312.so cpy/

      - name: Verify build
        run: |
          python -c "import cl; print('Cythonization successful')"
